# Generated by Django 3.2.9 on 2021-12-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20211123_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
